---
- name: Add deploy user
  user: name=deploy group=www-data state=present system=yes groups=sshlogin
  tags: deploy

- authorized_key: >
    user=deploy
    state=present
    key="{{lookup('file', '~/.ssh/id_rsa.pub')}}"
  tags: deploy