---
- name: Creating my droplet
  digital_ocean: >
    state=present
    ssh_key_ids={{ do_ssh_key_ids }}
    name={{ do_name }}
    size_id={{ do_size_id }}
    region_id={{ do_region_id }}
    image_id={{ do_image_id }}
    backups_enabled={{ do_backups_enabled }}
    unique_name={{ do_unique_name }}
  register: my_droplet
  tags: do

- name: Adding my new droplet IP in hosts file
  lineinfile: create=yes dest=hosts line={{ item }} state=present
  with_items:
    - '[production]'
    - '{{ my_droplet.droplet.ip_address }}'
  tags: do

- name: Gathering the public ssh host keys
  command: ssh-keyscan {{ my_droplet.droplet.ip_address }}
  register: ssh_host_my_droplet
  tags: do

- name: Adding public ssh host key in /.ssh/known_hosts
  lineinfile: >
    create=yes
    dest=~/.ssh/known_hosts
    mode=600
    line='{{ssh_host_my_droplet.stdout}}'
    state=present
  tags: do